#!/bin/sh

PYTHON_HOME="/Library/Frameworks/Python.framework/Versions/2.5"

# acprep, version 3.0
#
# This script configures my ledger source tree on my Mac OS/X machine.
# This is not necessary, however, since I keep all the files necessary
# for building checked in to the source tree.  Users can just type
# './configure && make'.  This script simply sets up the compiler and
# linker flags for all the various build permutations I use for
# testing and profiling.

LIBTOOLIZE=$(which glibtoolize 2>&1)

if [ -x "$LIBTOOLIZE" ]; then
    "$LIBTOOLIZE" --automake -f -c
else
    libtoolize --automake -f -c
fi

aclocal
autoheader
automake -a -c -f
autoconf


INCDIRS="-I/usr/local/include"
INCDIRS="$INCDIRS -I/usr/local/include/boost"
INCDIRS="$INCDIRS -I/sw/include"
INCDIRS="$INCDIRS -I/usr/include/httpd/xml"

LIBDIRS="-L/usr/local/lib"
LIBDIRS="$LIBDIRS -L/sw/lib"

SYSTEM=`uname -s`

if [ $SYSTEM = Linux ]; then
    CXXFLAGS="-pthread"
elif [ $SYSTEM = Solaris ]; then
    CXXFLAGS="-pthreads"
elif [ $SYSTEM = Darwin ]; then
    #CXXFLAGS="-arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
    CXXFLAGS="$CXXFLAGS -Wno-long-double"
    #LIBDIRS="$LIBDIRS -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk"
else
    CXXFLAGS=""
fi

# Building the command-line tool as a shared library is a luxury,
# since there are no clients except a GUI tool which might use it (and
# that is built again anyway by Xcode).
SWITCHES="--disable-shared --enable-pch"
CPPFLAGS="$INCDIRS"
LDFLAGS="$LIBDIRS"


while [ -n "$1" ]; do
  case "$1" in
    --debug)
	SWITCHES="$SWITCHES --enable-debug --enable-boost-sd"
	CPPFLAGS="$CPPFLAGS -D_GLIBCXX_DEBUG=1"
	CXXFLAGS="$CXXFLAGS -g" ;;

    --prof | --perf)
        CXXFLAGS="$CXXFLAGS -g -pg" ;;

    --python)
	if [ -d "$PYTHON_HOME" ]; then
	    SWITCHES="$SWITCHES --enable-python"
	    CPPFLAGS="$CPPFLAGS -I$PYTHON_HOME/include/python2.5"
	    LDFLAGS="$LDFLAGS -L$PYTHON_HOME/lib/python2.5/config"
	fi ;;

    --opt)
	CXXFLAGS="$CXXFLAGS -fomit-frame-pointer -O3 -fPIC" ;;
    --flat-opt)
	CXXFLAGS="$CXXFLAGS -fomit-frame-pointer -O3" ;;
    --safe-opt)
	CXXFLAGS="$CXXFLAGS -fomit-frame-pointer -O3 -fPIC -DDEBUG_LEVEL=1" ;;

    *)
	break ;;
  esac
  shift 1
done


HERE="$PWD"

if [ -d "$HOME/Products" ]; then
    version=""
    if [ -x pending/version ]; then
	version="-$(pending/version)"
    fi
    projdir="$HOME/Products/$(basename $HERE)$version"
    if [ ! -d "$projdir" ]; then
	mkdir -p "$projdir"
    fi
    cd "$projdir" || (echo "Cannot change to $projdir"; exit 1)
fi

"$HERE/configure" --srcdir="$HERE" \
    CPPFLAGS="$CPPFLAGS" CXXFLAGS="$CXXFLAGS $local_cxxflags" \
    LDFLAGS="$LDFLAGS" LIBS="$LIBS" $SWITCHES "$@"
