cognitive-complexity-threshold = 30
max-fn-params-bools = 3
type-complexity-threshold = 250
too-many-arguments-threshold = 7
single-char-binding-names-threshold = 4
too-many-lines-threshold = 100
msrv = "1.70.0"

# Allow certain patterns common in C++ FFI
allow-expect-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true