#!/bin/sh

errors=0

if [ ! -f utils/standard.dat ]; then
    exit 0
fi

#    "-G retire"
#    "-G ira"
#    "-G 401"

for test in \
    "-O nrl:checking" \
    "-O ^expenses"    \
    "-B 401"	      \
    "-V 401"	      \
    "-B ira"	      \
    "-V ira"	      \
    "-B retire"       \
    "-V retire"
do
  echo testing: $test
  python tests/confirm.py $test
  errors=`expr $errors + $?`
done

exit $errors
