#!/usr/bin/env python3
# Regression test for GitHub issue #2453:
# Python API xact.raw_posts should return only original (raw) postings,
# not postings generated by automated transactions.
# xact.posts should return all postings including generated ones.

import ledger

journal = ledger.read_journal_from_string("""
= /Food/
    (Assets:Cash)    $100

2012-03-01 KFC
    Expenses:Food    $100
    Assets:Credit
""")

for xact in journal.xacts:
    posts = list(xact.posts)
    raw = list(xact.raw_posts)
    print("post count: %d" % len(posts))
    for post in posts:
        print("%s %s" % (post.amount, post.account))
    print("raw post count: %d" % len(raw))
    for post in raw:
        print("%s %s" % (post.amount, post.account))
