#!/usr/bin/env python3
# Regression test for GitHub issue #2453:
# Python API xact.posts should return only original (raw) postings,
# not postings generated by automated transactions.

import ledger

# Test with a conditional automated transaction (= /Food/) that matches
# one posting and generates an extra (Assets:Cash) posting.
# xact.posts must show only the 2 original postings, not 3.
journal = ledger.read_journal_from_string("""
= /Food/
    (Assets:Cash)    $100

2012-03-01 KFC
    Expenses:Food    $100
    Assets:Credit
""")

for xact in journal.xacts:
    posts = list(xact.posts)
    print("post count: %d" % len(posts))
    for post in posts:
        print("%s %s" % (post.amount, post.account))
