CC = g++
CFLAGS = -g -Wall -pedantic

negativetest: negative.cpp ../../source/utf8.h ../../source/utf8/core.h ../../source/utf8/checked.h ../../source/utf8/unchecked.h
	$(CC) $(CFLAGS) negative.cpp -onegative
