/*
 * Copyright (c) 2003-2025, John Wiegley.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in the
 *   documentation and/or other materials provided with the distribution.
 *
 * - Neither the name of New Artisans LLC nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @addtogroup data
 */

/**
 * @file   account.h
 * @author John Wiegley
 *
 * @ingroup data
 *
 * @brief  Hierarchical account tree (chart of accounts)
 *
 * Defines the account_t class, which represents one node in the tree
 * that Ledger uses as its chart of accounts.  Account names use
 * colon-separated segments -- for example, @c Expenses:Food:Groceries
 * is a three-level path where "Expenses" is the top-level parent,
 * "Food" is a child of "Expenses", and "Groceries" is a leaf.
 *
 * Every journal has a single invisible root account (depth 0) whose
 * children are the top-level accounts the user defines.  Each account
 * holds the list of postings that affect it and, optionally, deferred
 * postings waiting for a UUID-matched transaction to arrive.
 *
 * During reporting the account tree is decorated with extended data
 * (xdata_t) that carries running totals, display flags, and
 * statistical details.  This data is allocated lazily and cleared
 * between report passes.
 */
#pragma once

#include <limits>

#include "scope.h"
#include "types.h"

namespace ledger {

using namespace boost::placeholders;

/// Map from UUID strings to lists of deferred postings awaiting that UUID.
using deferred_posts_map_t = std::map<string, posts_list>;

/**
 * @brief A node in the hierarchical chart of accounts.
 *
 * account_t represents one account in the account tree.  Accounts are
 * identified by colon-separated paths such as @c Assets:Bank:Checking.
 * Each node stores its local name ("Checking"), a pointer to its parent
 * ("Bank"), and a map of child accounts.
 *
 * Accounts accumulate postings: every post_t that debits or credits an
 * account is recorded in that account's posts list, which enables the
 * reporting engine to compute balances by iterating the list.
 *
 * account_t inherits from scope_t so that expressions like
 * @c account&nbsp;=~&nbsp;/Expenses/ can be evaluated with the account
 * as the evaluation context, giving expressions access to the account's
 * name, depth, totals, and statistics through the lookup() dispatch table.
 */
class account_t : public flags::supports_flags<>, public scope_t {
#define ACCOUNT_NORMAL 0x00 ///< No special flags; an ordinary user-defined account.
#define ACCOUNT_KNOWN                                                                              \
  0x01 ///< Account was declared with the `account` directive (for --strict/--pedantic validation).
#define ACCOUNT_TEMP 0x02 ///< Temporary account created during reporting (not persisted).
#define ACCOUNT_GENERATED                                                                          \
  0x04 ///< Account was generated by the engine and never appeared in the journal.

public:
  account_t* parent;     ///< Parent node in the account tree (nullptr for root).
  string name;           ///< Local name of this account (e.g., "Checking", not the full path).
  optional<string> note; ///< Optional note from the `account` directive's comment.
  unsigned short depth;  ///< Nesting level: root=0, Assets=1, Assets:Bank=2, etc.
  accounts_map accounts; ///< Child accounts keyed by local name.
  posts_list posts;      ///< Postings that affect this account.
  optional<deferred_posts_map_t>
      deferred_posts; ///< Postings waiting for a UUID-matched transaction to arrive.
  std::optional<expr_t>
      value_expr; ///< Custom valuation expression overriding commodity-level valuation.

  mutable string _fullname; ///< Cached colon-joined full name, computed lazily by fullname().

  account_t(account_t* _parent = nullptr, const string& _name = "",
            const optional<string>& _note = none)
      : supports_flags<>(), scope_t(), parent(_parent), name(_name), note(_note),
        depth(static_cast<unsigned short>(parent ? parent->depth + 1 : 0)) {
    if (parent && parent->depth == std::numeric_limits<unsigned short>::max())
      throw std::runtime_error("Account hierarchy too deep");
    TRACE_CTOR(account_t, "account_t *, const string&, const string&");
  }
  // Note: copy is intentionally shallow — posts and deferred_posts are
  // NOT copied. The copy shares the same parent and children map but
  // has an independent (empty) posting history.
  account_t(const account_t& other)
      : supports_flags<>(other.flags()), scope_t(), parent(other.parent), name(other.name),
        note(other.note), depth(other.depth), accounts(other.accounts) {
    TRACE_CTOR(account_t, "copy");
  }
  ~account_t() override;

  string description() override { return string(_("account ")) + fullname(); }

  operator string() const { return fullname(); }

  /**
   * @brief Return the full colon-separated account name (e.g., "Expenses:Food:Groceries").
   *
   * The result is cached in _fullname for repeated access.  Walking up the
   * parent chain from this node to the root (whose name is empty) and joining
   * each segment with ':' produces the canonical account path that users see
   * in reports and can use in expressions.
   */
  string fullname() const;

  /**
   * @brief Return a display-collapsed account name for indented reports.
   *
   * Walks up the parent chain, prepending parent names until a "branching
   * point" is reached -- an ancestor that has multiple displayed children or
   * is itself displayed.  This produces names like "Food:Groceries" instead
   * of the full "Expenses:Food:Groceries" when "Expenses" has only one
   * displayed child path.
   *
   * @param flat  If true, always return the full path (no collapsing).
   */
  string partial_name(bool flat = false) const;

  void add_account(account_t* acct) { accounts.insert(accounts_map::value_type(acct->name, acct)); }
  bool remove_account(account_t* acct) {
    accounts_map::size_type n = accounts.erase(acct->name);
    return n > 0;
  }

  /**
   * @brief Look up or create an account by colon-separated name.
   *
   * Splits @p name on ':' and walks/creates the tree recursively.
   * For "Assets:Bank:Checking", it finds or creates "Assets" as a
   * child of this node, then "Bank" as a child of "Assets", then
   * "Checking" as a child of "Bank".  Newly created accounts inherit
   * the ACCOUNT_TEMP and ACCOUNT_GENERATED flags from their parent.
   *
   * @param name         Colon-separated account path.
   * @param auto_create  If false, return nullptr instead of creating missing accounts.
   * @return Pointer to the (leaf) account, or nullptr if not found and auto_create is false.
   */
  [[nodiscard]] account_t* find_account(string_view name, bool auto_create = true);

  /**
   * @brief Find an account whose full name matches a regular expression.
   *
   * Performs a depth-first search of the account tree starting from this
   * node, returning the first account whose fullname() matches @p regexp.
   *
   * @return Pointer to the matching account, or nullptr if none matches.
   */
  [[nodiscard]] account_t* find_account_re(const string& regexp);

  using accounts_map_seconds_iterator =
      transform_iterator<function<account_t*(accounts_map::value_type&)>, accounts_map::iterator>;

  accounts_map_seconds_iterator accounts_begin() {
    return make_transform_iterator(accounts.begin(),
                                   boost::bind(&accounts_map::value_type::second, _1));
  }
  accounts_map_seconds_iterator accounts_end() {
    return make_transform_iterator(accounts.end(),
                                   boost::bind(&accounts_map::value_type::second, _1));
  }

  /** @brief Append a posting and invalidate cached totals up to the root. */
  void add_post(post_t* post);

  /**
   * @brief Queue a posting to be applied when its UUID-matched transaction arrives.
   *
   * Used by automated transactions that reference a specific UUID.  The
   * posting is held in deferred_posts until apply_deferred_posts() or
   * UUID deduplication in add_xact() resolves it.
   */
  void add_deferred_post(const string& uuid, post_t* post);

  /** @brief Flush all deferred postings into their target accounts, recursively. */
  void apply_deferred_posts();

  /** @brief Remove a posting from this account and invalidate cached iterators. */
  bool remove_post(post_t* post);

  posts_list::iterator posts_begin() { return posts.begin(); }
  posts_list::iterator posts_end() { return posts.end(); }

  /**
   * @brief Dispatch table for expression function lookups.
   *
   * Maps function names used in value expressions (e.g., "amount",
   * "total", "depth", "parent") to the corresponding getter functions.
   * This is what allows format strings like @c %(account) and
   * @c %(total) to resolve against an account context.
   */
  expr_t::ptr_op_t lookup(const symbol_t::kind_t kind, const string& name) override;

  [[nodiscard]] bool valid() const;

  friend class journal_t;

  /**
   * @brief Extended data attached to an account during reporting.
   *
   * xdata_t is allocated lazily (only when the account is first
   * touched by the reporting pipeline) and carries the running totals,
   * display-state flags, and statistical details that the reporting
   * engine needs.  It is cleared between report passes via clear_xdata().
   */
  struct xdata_t : public supports_flags<> {
#define ACCOUNT_EXT_SORT_CALC 0x01        ///< Sort expression has been evaluated for this account.
#define ACCOUNT_EXT_HAS_NON_VIRTUALS 0x02 ///< Account has at least one non-virtual posting.
#define ACCOUNT_EXT_HAS_UNB_VIRTUALS 0x04 ///< Account has at least one unbalanced virtual posting.
#define ACCOUNT_EXT_AUTO_VIRTUALIZE 0x08  ///< Auto-virtualization is active for this account.
#define ACCOUNT_EXT_VISITED 0x10  ///< Account was visited by the report walker (totals are valid).
#define ACCOUNT_EXT_MATCHING 0x20 ///< Account matches the current report query.
#define ACCOUNT_EXT_TO_DISPLAY 0x40 ///< Account is selected for display in the current report.
#define ACCOUNT_EXT_DISPLAYED 0x80  ///< Account has already been output in the current report.

    /**
     * @brief Statistical and summary details for an account.
     *
     * details_t tracks post counts, date ranges (earliest/latest),
     * timeclock check-in/check-out timestamps, referenced accounts
     * and payees, and source file paths.  Two instances exist in
     * xdata_t: self_details (this account's own postings) and
     * family_details (this account plus all descendants).
     *
     * Lazy evaluation is controlled by two booleans:
     *   - @c gathered: if true, update() has been called for all posts.
     *   - @c calculated: if true, the total/real_total values are current.
     *
     * The last_post and last_reported_post iterators support incremental
     * accumulation in amount(): on each call, iteration resumes from where
     * it left off rather than re-scanning from the beginning.
     */
    struct details_t {
      value_t total;      ///< Accumulated total (real + virtual postings).
      value_t real_total; ///< Accumulated total of non-virtual postings only.
      bool calculated;    ///< True once total/real_total have been computed.
      bool gathered;      ///< True once update() has processed all known posts.

      std::size_t posts_count;            ///< Total number of postings.
      std::size_t posts_virtuals_count;   ///< Number of virtual postings.
      std::size_t posts_cleared_count;    ///< Number of cleared postings.
      std::size_t posts_last_7_count;     ///< Postings within the last 7 days.
      std::size_t posts_last_30_count;    ///< Postings within the last 30 days.
      std::size_t posts_this_month_count; ///< Postings in the current calendar month.

      date_t earliest_post;         ///< Date of the earliest posting.
      date_t earliest_cleared_post; ///< Date of the earliest cleared posting.
      date_t latest_post;           ///< Date of the most recent posting.
      date_t latest_cleared_post;   ///< Date of the most recent cleared posting.

      datetime_t earliest_checkin;  ///< Earliest timeclock check-in timestamp.
      datetime_t latest_checkout;   ///< Latest timeclock check-out timestamp.
      bool latest_checkout_cleared; ///< Whether the latest check-out was cleared.

      std::set<path> filenames;             ///< Source files that contributed postings.
      std::set<string> accounts_referenced; ///< Full names of accounts referenced by postings.
      std::set<string> payees_referenced;   ///< Payee names referenced by postings.

      optional<posts_list::const_iterator>
          last_post; ///< Resume point for incremental accumulation over posts.
      optional<posts_list::const_iterator>
          last_reported_post; ///< Resume point for incremental accumulation over reported_posts.

      details_t()
          : calculated(false), gathered(false),

            posts_count(0), posts_virtuals_count(0), posts_cleared_count(0), posts_last_7_count(0),
            posts_last_30_count(0), posts_this_month_count(0), latest_checkout_cleared(false) {
        TRACE_CTOR(account_t::xdata_t::details_t, "");
      }
      // A copy copies nothing
      details_t(const details_t&)
          : calculated(false), gathered(false),

            posts_count(0), posts_virtuals_count(0), posts_cleared_count(0), posts_last_7_count(0),
            posts_last_30_count(0), posts_this_month_count(0), latest_checkout_cleared(false) {
        TRACE_CTOR(account_t::xdata_t::details_t, "copy");
      }
      details_t& operator=(const details_t&) = default;
      ~details_t() noexcept { TRACE_DTOR(account_t::xdata_t::details_t); }

      /** @brief Merge another details_t into this one (used for family aggregation). */
      details_t& operator+=(const details_t& other);

      /**
       * @brief Update statistics with data from a single posting.
       *
       * Increments counters, extends date ranges, records timeclock
       * data, and (when @p gather_all is true) collects referenced
       * account names, payee names, and source file paths.
       */
      void update(post_t& post, bool gather_all = false);
    };

    details_t self_details;    ///< Statistics for this account's own postings only.
    details_t family_details;  ///< Statistics for this account plus all descendant accounts.
    posts_list reported_posts; ///< Postings redirected to this account during reporting (e.g., by
                               ///< display filters).

    std::list<sort_value_t> sort_values; ///< Cached sort-key values for the accounts report.

    xdata_t() : supports_flags<>() { TRACE_CTOR(account_t::xdata_t, ""); }
    xdata_t(const xdata_t& other)
        : supports_flags<>(other.flags()), self_details(other.self_details),
          family_details(other.family_details), sort_values(other.sort_values) {
      TRACE_CTOR(account_t::xdata_t, "copy");
    }
    ~xdata_t() noexcept { TRACE_DTOR(account_t::xdata_t); }
  };

  /// Optional extended data, allocated lazily during reporting.  This is a
  /// memory-saving measure: most accounts never need xdata outside of an
  /// active report pass, so allocation is deferred until first access.
  mutable optional<xdata_t> xdata_;

  bool has_xdata() const { return static_cast<bool>(xdata_); }

  /** @brief Recursively clear all extended data from this account and its children. */
  void clear_xdata();

  /**
   * @brief Reset display-related xdata while preserving accumulated totals.
   *
   * Clears display flags (TO_DISPLAY, DISPLAYED, SORT_CALC, etc.) and
   * resets family_details so total() will recalculate, but keeps
   * ACCOUNT_EXT_VISITED and self_details intact so that amounts
   * accumulate correctly across multiple display groups in the same report.
   */
  void clear_display_state();
  xdata_t& xdata() {
    if (!xdata_)
      xdata_ = xdata_t();
    return *xdata_;
  }
  const xdata_t& xdata() const {
    assert(xdata_);
    return *xdata_;
  }

  /**
   * @brief Compute this account's own balance from visited postings.
   *
   * Iterates the posts list (and reported_posts) counting only postings
   * marked POST_EXT_VISITED.  Uses last_post/last_reported_post
   * iterators for incremental accumulation: each call resumes from where
   * the previous call left off.  Posts are marked POST_EXT_CONSIDERED
   * after being counted to prevent double-counting across calls.
   *
   * @param real_only  If true, return only the non-virtual total.
   * @param expr       Optional valuation expression applied to each posting.
   */
  value_t amount(const optional<bool> real_only = false,
                 const optional<expr_t&>& expr = none) const;

  /**
   * @brief Unconditional sum of all posting amounts (ignores visit flags).
   *
   * Unlike amount(), this sums every posting in the account regardless
   * of whether it was visited by the reporting pipeline.  Useful for
   * balance assertions during parsing.
   */
  value_t self_total(bool real_only = false) const;

  /**
   * @brief Recursive family total: this account's amount() plus all children's total().
   *
   * Cached via family_details.calculated to avoid redundant tree walks.
   */
  value_t total(const optional<expr_t&>& expr = none) const;

  /**
   * @brief Lazily gather and return statistics for this account's own postings.
   * @param gather_all  If true, also collect file paths, account names, and payees.
   */
  const xdata_t::details_t& self_details(bool gather_all = true) const;

  /**
   * @brief Lazily gather and return statistics for this account and all descendants.
   * @param gather_all  If true, also collect file paths, account names, and payees.
   */
  const xdata_t::details_t& family_details(bool gather_all = true) const;

  bool has_xflags(xdata_t::flags_t flags) const { return xdata_ && xdata_->has_flags(flags); }
  bool children_with_xdata() const;
  std::size_t children_with_flags(xdata_t::flags_t flags) const;
};

std::ostream& operator<<(std::ostream& out, const account_t& account);

/** @brief Serialize an account and its children to a Boost property tree (XML output). */
void put_account(property_tree::ptree& pt, const account_t& acct,
                 const function<bool(const account_t&)>& pred);

/// Comparator for ordering accounts by full name in std::map/std::set.
struct account_compare {
  bool operator()(const account_t& lhs, const account_t& rhs) const {
    return (lhs.fullname().compare(rhs.fullname()) < 0);
  }
};

} // namespace ledger
